import PDFDocument from "pdfkit";
import type { CompanyReport } from "@/types";

function collectPdfBuffer(doc: InstanceType<typeof PDFDocument>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}

function ensureSpace(doc: InstanceType<typeof PDFDocument>, needed = 80) {
  if (doc.y + needed > doc.page.height - 60) {
    doc.addPage();
  }
}

export async function generatePdfReport(report: CompanyReport): Promise<Buffer> {
  const doc = new PDFDocument({ margin: 50, size: "A4" });
  const bufferPromise = collectPdfBuffer(doc);

  const accent = "#4f46e5";
  const text = "#1e293b";
  const muted = "#64748b";
  const margin = 50;
  const width = doc.page.width - margin * 2;

  const section = (title: string) => {
    ensureSpace(doc, 60);
    doc.moveDown(0.8);
    doc.fontSize(12).font("Helvetica-Bold").fillColor(accent).text(title);
    doc
      .moveTo(margin, doc.y + 2)
      .lineTo(doc.page.width - margin, doc.y + 2)
      .strokeColor("#cbd5e1")
      .lineWidth(1)
      .stroke();
    doc.moveDown(0.6);
    doc.fillColor(text);
  };

  const field = (label: string, value: string) => {
    ensureSpace(doc, 20);
    doc.fontSize(10).font("Helvetica-Bold").fillColor(muted).text(`${label}: `, {
      continued: true,
    });
    doc.font("Helvetica").fillColor(text).text(value || "Not available");
  };

  const bulletList = (items: string[]) => {
    if (items.length === 0) {
      doc.fontSize(10).font("Helvetica").fillColor(muted).text("Not available");
      return;
    }
    items.forEach((item) => {
      ensureSpace(doc, 20);
      doc.fontSize(10).font("Helvetica").fillColor(text).text(`• ${item}`, {
        indent: 10,
        width,
      });
    });
  };

  doc.fontSize(20).font("Helvetica-Bold").fillColor(accent).text("Company Research Report");
  doc.moveDown(0.3);
  doc.fontSize(10).font("Helvetica").fillColor(muted).text(
    `Generated on ${new Date(report.generatedAt).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })}`
  );
  doc.moveDown(1);

  section("Company Overview");
  field("Name", report.companyName);
  field("Website", report.website);
  field("Phone", report.phone);
  field("Address", report.address);

  section("Business Information");
  field("Industry", report.industry);
  field("Founded", report.founded);
  field("Headquarters", report.headquarters);

  section("Products & Services");
  bulletList(report.productsServices);

  section("AI Summary");
  ensureSpace(doc, 40);
  doc.fontSize(10).font("Helvetica").fillColor(text).text(report.summary || "Not available", {
    align: "justify",
    width,
  });

  section("Pain Points");
  bulletList(report.painPoints);

  section("SWOT Analysis");
  const swotGroups = [
    ["Strengths", report.swot.strengths],
    ["Weaknesses", report.swot.weaknesses],
    ["Opportunities", report.swot.opportunities],
    ["Threats", report.swot.threats],
  ] as const;

  swotGroups.forEach(([label, items]) => {
    ensureSpace(doc, 30);
    doc.fontSize(10).font("Helvetica-Bold").fillColor(accent).text(label);
    doc.moveDown(0.2);
    bulletList(items);
    doc.moveDown(0.4);
  });

  section("Competitors");
  if (report.competitors.length === 0) {
    doc.fontSize(10).font("Helvetica").fillColor(muted).text("No competitors identified.");
  } else {
    report.competitors.forEach((comp, i) => {
      ensureSpace(doc, 30);
      doc.fontSize(10).font("Helvetica-Bold").fillColor(text).text(`${i + 1}. ${comp.name}`);
      doc.font("Helvetica").fillColor(muted).text(comp.website, { link: comp.website });
      doc.moveDown(0.3);
    });
  }

  section("Pages Crawled");
  if (report.pagesCrawled.length === 0) {
    doc.fontSize(10).font("Helvetica").fillColor(muted).text("No pages crawled.");
  } else {
    report.pagesCrawled.forEach((url) => {
      ensureSpace(doc, 20);
      doc.fontSize(9).font("Helvetica").fillColor(text).text(`• ${url}`, { link: url, width });
    });
  }

  section("Sources");
  if (report.sources.length === 0) {
    doc.fontSize(10).font("Helvetica").fillColor(muted).text("No sources recorded.");
  } else {
    report.sources.forEach((source) => {
      ensureSpace(doc, 30);
      doc.fontSize(10).font("Helvetica-Bold").fillColor(text).text(source.title);
      doc.fontSize(9).font("Helvetica").fillColor(muted).text(source.url, { link: source.url, width });
      doc.moveDown(0.3);
    });
  }

  doc
    .fontSize(8)
    .fillColor(muted)
    .text(
      "This report was generated by AI using publicly available information. Verify critical details independently.",
      margin,
      doc.page.height - 40,
      { align: "center", width }
    );

  doc.end();
  return bufferPromise;
}
